[package]
name = "minesweeper-ai"
version = "0.1.0"
edition = "2021"

[build]
profiler = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miinaharava = { path = "../miinaharava" }